name: Build Redis HTTP Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manual trigger

jobs:
  build-library:
    name: Build libredis_http.so for Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential pkg-config libssl-dev
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: '.'
        
    - name: Build the library
      run: cargo build --release
      
    - name: Run tests
      run: cargo test --lib
      
    - name: Verify library
      run: |
        echo "=== Library Information ==="
        file target/release/libredis_http.so
        echo ""
        echo "=== Library Size ==="
        ls -lh target/release/libredis_http.so
        echo ""
        echo "=== Library Dependencies ==="
        ldd target/release/libredis_http.so
        echo ""
        echo "=== Library Symbols ==="
        nm -D target/release/libredis_http.so | grep -E "(RedisModule|http)" | head -10
        
    - name: Upload library artifact
      uses: actions/upload-artifact@v3
      with:
        name: libredis_http.so
        path: target/release/libredis_http.so
        retention-days: 90
        
    - name: Create download link
      run: |
        echo "## 📦 Library Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Library:** \`libredis_http.so\`" >> $GITHUB_STEP_SUMMARY
        echo "**Size:** $(ls -lh target/release/libredis_http.so | awk '{print $5}')" >> $GITHUB_STEP_SUMMARY
        echo "**Architecture:** x86_64-unknown-linux-gnu" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📥 Download" >> $GITHUB_STEP_SUMMARY
        echo "Go to the **Actions** tab → **Build Redis HTTP Library** → **libredis_http.so** artifact" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🚀 Usage Instructions" >> $GITHUB_STEP_SUMMARY
        echo "1. Download the \`libredis_http.so\` file" >> $GITHUB_STEP_SUMMARY
        echo "2. Copy to your Ubuntu server: \`scp libredis_http.so user@server:/path/to/redis/modules/\`" >> $GITHUB_STEP_SUMMARY
        echo "3. Add to redis.conf: \`loadmodule /path/to/libredis_http.so\`" >> $GITHUB_STEP_SUMMARY
        echo "4. Restart Redis: \`sudo systemctl restart redis\`" >> $GITHUB_STEP_SUMMARY
        echo "5. Test: \`curl -u \\\":\\\" http://localhost:4887/GET/test\`" >> $GITHUB_STEP_SUMMARY